version: '3'

services:
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible:/ansible2
