- name: Run Java Applications
  hosts: localhost
  become: true

  tasks:
    - name: Run Java Spring Boot Server
      shell: ( ( nohup java -jar server.jar>/dev/null 2>&1 ) & ) && sleep 10

    - name: Check Health
      shell: curl http://127.0.0.1:1234/
